# Generated by Django 5.0 on 2024-03-04 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('short_link', models.CharField(blank=True, max_length=5, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, null=True)),
                ('visit_number', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
