# Generated by Django 5.0 on 2024-03-06 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='link',
            field=models.TextField(unique=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
