# Generated by Django 5.0 on 2024-03-07 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_shortlink_link_alter_shortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='link',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
